# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EngramExplorer < Formula
  desc "Local web dashboard for exploring Engram memory database"
  homepage "https://github.com/AlvaroQ/engram-explorer"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AlvaroQ/engram-explorer/releases/download/v0.1.0/engram-explorer_0.1.0_darwin_amd64.tar.gz"
      sha256 "3dff9f3995e3e3bd42ddacb041721dc21baa7a0bca1c9378a5698768cf8cab2c"

      define_method(:install) do
        bin.install "engram-explorer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AlvaroQ/engram-explorer/releases/download/v0.1.0/engram-explorer_0.1.0_darwin_arm64.tar.gz"
      sha256 "9364f8df068aed531208c3dfeafc7db231e1cb472a1d9972ad2d8e6b4e0003db"

      define_method(:install) do
        bin.install "engram-explorer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AlvaroQ/engram-explorer/releases/download/v0.1.0/engram-explorer_0.1.0_linux_amd64.tar.gz"
      sha256 "2e5c1a61c612173fe7170e5bfa2253dae7d4c2c77296b58b5d5fb7f658c6952d"
      define_method(:install) do
        bin.install "engram-explorer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AlvaroQ/engram-explorer/releases/download/v0.1.0/engram-explorer_0.1.0_linux_arm64.tar.gz"
      sha256 "21c4040bb9b5af29ae8761a0cd7ee2628902a42c52569fdd75f1730db421188b"
      define_method(:install) do
        bin.install "engram-explorer"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/engram-explorer --version")
  end
end
